[package]
name = "capsules"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
kernel = { path = "../kernel" }
enum_primitive = { path = "../libraries/enum_primitive" }
tickv = { path = "../libraries/tickv" }

[features]
vendor_hid = []
